version: "3.9"

services:
  frontend:
    build:
      context: ./client
    container_name: netflix-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    container_name: netflix-backend
    ports:
      - "8081:8081"
    env_file:
      - ./server/.env
